
#
client localhost {
        ipv4addr = * #127.0.0.1 # any.  127.0.0.1 == localhost
        proto = *
        secret = <REPLACE_WITH_RADIUS_SHARED_SECRET>
        require_message_authenticator = no
        shortname = localhost
}
#
client hub-01 {
        ipv4addr        = 172.28.28.2
        secret = <REPLACE_WITH_RADIUS_SHARED_SECRET>
        shortname       = hub-01
}
#
client hub-02 {
        ipv4addr  = 172.28.28.3
        secret = <REPLACE_WITH_RADIUS_SHARED_SECRET>
        shortname = hub-02
}
